### PR TITLE
Explicitly import `index.js`

### PR DESCRIPTION
**Pull request by i-am-the-slime**
Because in my tests node cries around (heult rum):
`  code: 'ERR_UNSUPPORTED_DIR_IMPORT',`

### CODE REVIEW

**Comment by andys8** [comment]
Oha, I'm a bit surprised `/index.js` would be necessary and make a difference, but probably can do. Not how I would expect it to import.

Screenshot_2023-02-22-17-21-43-96_4d38fce200f96aeac5e860e739312e76


Have to take a look why everything gets resorted. Probably missing in the script to have determinism in the order if icons.

**Comment by andys8** [comment]
Still looking into this, since fixing it to `index.js` would exclude `index.esm.js`. I'm wondering if this could lead to new issues. Or if it is fixed, if it should actually be the `index.esm.js` version.

The other way would be `--experimental-specifier-resolution=node` as argument for node, but if appending the specific file is a fix, I would merge do it (because it's easier to use). 

@i-am-the-slime Could you double check if `index.esm.js` would also work for your project?

**Comment by i-am-the-slime** [comment]
Just looking at this. Didn't see the notification, sorry. 
`--experimental-specifier-resolution=node ` is unfortunately already deprecated again.
I think yes, we should try with `index.esm.js` and I will try that in my branch now.

**Comment by i-am-the-slime** [comment]
I don't know anymore:
```
SyntaxError: Named export 'BsAlarm' not found. The requested module 'react-icons/bs/index.esm.js' is a CommonJS module, which may not support all module.exports as named exports.
```

**Comment by i-am-the-slime** [comment]
I could work around it something like this in `package.json`:

```json
    "test": "spago build && esbuild test.mjs --platform=node --bundle > test.js && node test.js",
```

And `test.mjs` is just the stupid:

```
import { main } from "./output/Test.Main/index.js"

main()
```

**Comment by i-am-the-slime** [comment]
image
And then I get this

**Comment by andys8** [comment]
So, `index.esm.js` didn't work? Can you share details about the test runner / setup?

I mean we can go for commonjs. I'm just a bit afraid there is chance it will break regular projects.

**Comment by i-am-the-slime** [comment]
I think I'm hitting this:
https://github.com/vercel/next.js/issues/39375

**Comment by i-am-the-slime** [comment]
@andys8 I think the best "solution" is to use the folder imports as on main. None of the other things work properly in one environment or another.

**Pull request closed without merging**
